### ISSUE TITLE
Trackpad issues with Mojave 10.14.2

### ISSUE THREAD

**Issue by kraftpunk97-zz** [kauefontes/INSPIRON-5567-MOJAVE#1]
Hi. I have the Dell Inspiron 15 5567 with the Skylake Core i3 chip and 4GB RAM. I can't get certain gestures to work with my trackpad though. I have VoodooPS2Controller.kext just like you. But my trackpad isn't "detected" by the OS. [I also made a thread about it on tonymacx86.com](https://www.tonymacx86.com/threads/trouble-enabling-tap-to-click-double-tap-for-secondary-click-and-tap-to-drag-for-mojave.270151/) Is your touchpad working? I only need the tap to click, two finger tap for secondary click and tap to drag, but it's been a lot of trouble for me to get it working...

**Comment by kauefontes** [comment]
Bro, everything works great(except Dedicaded GPU and WIFi), trackpad works fine.

My machine was a Inspiron 5567 i7-7500u / 8gb of ram.

Do you tried use my EFI ? probably it will work just fine in your pc. My touchpad worked OOB.

**Comment by kauefontes** [comment]
@MatchesMalonee

**Comment by kraftpunk97-zz** [comment]
Are trackpad gestures working? "tap to drag" is enabled?

When you have to click, do you simply have to tap the trackpad (like in a touchscreen), or do you have to press the trackpad button?

Similarly, when you need to drag an item across the screen, do you simply double tap the trackpad surface and move your finger across the trackpad, or do you have to press the trackpad down with one finger, and use the other finger to move the item across the screen?

**Comment by kauefontes** [comment]
Yeah, even multitouch features are working. Everything works really great in mojave with these EFI settings.

**Comment by kraftpunk97-zz** [comment]
The issue has been fixed. Thank you for your time.
I had to change the stock Trackpad preference pane and replace it with one from El Capitan. After a few days the "Trackpad Options..." button appeared in Accessibility > Mouse and Trackpad.

**Comment by kauefontes** [comment]
Nice bro!
