### ISSUE TITLE
Placa de rede wifi hackintosh mojave

### ISSUE THREAD

**Issue by lfontesc** [kauefontes/INSPIRON-5567-MOJAVE#2]
Boa noite, você conseguiu ativar a placa de rede wifi que vem no dell 5567 ? 

Segue modelo da placa, Qualcomm QCA9565 802.11b/g/n Wireless Adapter

**Comment by kauefontes** [comment]
Hi, @lfontesc !

Usually this adapter isn't supported on MacOs, to get wifi working you should switch your adapter.

I recommend combo adapters from Broadcom, works great with macOS!

Please, use English on your issues and questions, it will help a lot more people to find out solutions for similar problems. =D

Thank you.
