### ISSUE TITLE
Reboot after 2/3 progress bar.

### ISSUE THREAD

**Issue by lfelipeserrano** [kauefontes/INSPIRON-5567-MOJAVE#3]
I have a Dell Inspiron 5567 with a i7 7500U, 8gb ram, I can enter in clover but after 2/3 of the progress bar the laptop just restart, currently I am in High Sierra, with your EFI files for that version, any idea of how can I fix that?

**Comment by kauefontes** [comment]
Bro, this repository and it's files are for the Mojave version, there is no support to high sierra in this repo. I recomend you upgrade to Mojave and give it a try.
If you insist in this version. please take a look on my other repository, destinated for the High Sierra( https://github.com/kauefontes/INSPIRON-5567-HIGH-SIERRA )
